Custom text feilds
blueappsgroup/finelf-form-components pull request #7
Opened 2020-09-17 14:37 UTC by dominika-czarniewska

Tutaj jest wszystko z pola typu text oprócz:
1. walidacja numeru dowodu osobistego 
2.  walidacja iban
mam to prawie skończone, ale ten cały kod walidacji wygląda jak kupa + musze dodac typowanie zeby to wgl pushnąć.

2020-09-18 10:05 UTC, tomaszbfinelf approved these changes
ladnie poprawione jeśli validacje działają to wszystko git

2020-09-22 12:59 UTC, msolecki commented on src/components/FormInput/ApartmentNumberField.tsx
> +import { validateHouseNumber } from './validate'
niech validacja i komponent sie nazywa tak samo

2020-09-22 12:59 UTC, msolecki commented on src/components/FormInput/CompanyTaxField.tsx
> +const CompanyNameField = () => (
inna nazwa

2020-09-22 13:00 UTC, msolecki commented on src/components/FormInput/CompanyTaxField.tsx
> +import { validateCompanyTax } from './validate'
tax number

2020-09-22 13:00 UTC, msolecki commented on src/components/FormInput/PeselField.tsx
> +    name="id_code"
zly name

2020-09-22 13:01 UTC, msolecki commented on src/components/FormInput/CompanyTaxField.tsx
> +    name="company_tax_id"
nie id tylko number

2020-09-22 13:01 UTC, msolecki commented on src/components/FormInput/CityNameField.tsx
> +    name="text_city"
czemu text_city?

2020-09-22 13:02 UTC, msolecki commented on src/components/FormInput/ZipCodeField.tsx
> +    name="text_zip"
tu tez ten text_ potrzebne ?

2020-09-22 13:04 UTC, msolecki commented on src/components/FormInput/validateHelpers.ts
> +      if (getLetterValue(idNumber[i]) < 10) return false
dodawaj {} w ifach nawet jak sa jednolinijkowe (nizej tez)

2020-09-22 13:34 UTC, dominika-czarniewska commented on src/components/FormInput/ZipCodeField.tsx
> +    name="text_zip"
te name dodawane sa na podstawie excela i tam tak to się nazywa
![image](https://user-images.githubusercontent.com/47636785/93889148-25cd1c00-fce9-11ea-9ec7-a37027670398.png)

2020-09-22 13:36 UTC, dominika-czarniewska commented on src/components/FormInput/validateHelpers.ts
> +      if (getLetterValue(idNumber[i]) < 10) return false
tutaj mogę dodać, ale przy commitach mamy i tak narzucone formatowanie,w eic nie wiem czy to domyslnie nie wywali mi tego

2020-09-22 14:05 UTC, tomaszbfinelf requested changes

2020-09-22 14:05 UTC, tomaszbfinelf commented on src/components/FormInput/BankAccountNumberField.tsx
> +const BankAccountNumberField = () => (
poprzekazuj propsy w komponentach bo tak nawet name nie bedzie mozna zmienic a czsem sie przyda w tym i innych

2020-09-24 09:50 UTC, merged