Range slider
blueappsgroup/finelf-form-components pull request #9
Opened 2020-09-21 14:24 UTC by AdrianRewajBlueApps

2020-09-22 08:12 UTC, msolecki commented on src/components/FormInput/base.tsx
> +export const BaseRangeField: (props: RangeFieldWrapProps) => ReactElement = ({
mamy wszedzie takie formatowanie ?

2020-09-22 08:34 UTC, tomaszbfinelf requested changes

2020-09-22 08:34 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> + background-color: ${(props: StyledProps): string => props.theme.submitButtonBgColor};
submitButtonBgColor to sa kolory buttonow to musi byc osobny konfigurowalny kolor rangeFillBgColor i defaultowo daejsz taki kolor jak chcesz tu i tam gdzie sie powtarza

2020-09-22 08:34 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> +                                                                field,
co się stało z tabami ustaw edytor na 2 spacje

2020-09-22 08:34 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> +export const BaseRangeField: (props: RangeFieldWrapProps) => ReactElement = ({
raczej nie

2020-09-22 08:34 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> +            <SliderDiv>
nie sider div tylko sliderwrapper np.

2020-09-22 08:34 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> +        setValue(value)
nie wiem po co ten setTimeout sprwdzenie tego stuffu mozna zrobic przed setValue chyba zę ma to jakiś zamysł

2020-09-22 13:27 UTC, msolecki commented
@tomaszbfinelf sprawdz i mozna puszczac jak ok

2020-09-22 14:11 UTC, tomaszbfinelf requested changes

2020-09-22 14:11 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> +    field.value = parseInt(e.target.value) || 0
tu lepiej let value zamiast nadpiswyac  field.value i tam nizej (...values, [field.name]: value) nie modyfikuj tego co przychodzi z propsow bo to sa refernecje do obiektu i jak bedzie jakis observer zapiety to sie wyjebie

2020-09-23 11:32 UTC, tomaszbfinelf requested changes

2020-09-23 11:32 UTC, tomaszbfinelf commented on src/components/FormInput/base.tsx
> +    values[field.name] = value
to co w porpzednim pr nie modyfikuj values

2020-09-23 14:21 UTC, tomaszbfinelf approved these changes

2020-09-24 07:59 UTC, merged